- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v1.2.3
  hooks:
    - id: check-json
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: debug-statements
    - id: end-of-file-fixer
    - id: check-ast
# -   repo: https://github.com/pre-commit/mirrors-isort
    # sha: 'v4.3.4'  # Use the sha / tag you want to point at
    # hooks:
    # -   id: isort
-   repo: https://github.com/pre-commit/mirrors-yapf
    sha: 'v0.21.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: yapf
